name: Retrain Model
on:
  push:
    paths:
      - 'data/WA_Fn-UseC_-Telco-Customer-Churn.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run retrain script
        run: |
          python scripts/data_preprocessing.py

      # Lightstep Pre-Deploy Check (optional step)
      - name: Lightstep Pre-Deploy Check
        uses: lightstep/lightstep-action-predeploy@v0.2.6
        with:
          lightstep_organization: # optional
          lightstep_project: # optional
          lightstep_api_key: # optional
          rollbar_api_token: # optional
          pagerduty_api_token: # optional
          rollup_conditions: # optional
          disable_comment: # optional
