name: Retrain Model
on:
  push:
    paths:
      - 'data/WA_Fn-UseC_-Telco-Customer-Churn.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run retrain script
        run: |
          python scripts/data_preprocessing.py

      # Optional: Send a notification to the GitHub email account
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          from: ${{ secrets.GITHUB_EMAIL }}  # GitHub email address
          to: ${{ secrets.GITHUB_EMAIL }}    # GitHub email address
          subject: 'Model Retraining Complete'
          body: 'The retraining process has been successfully completed.'
          smtp-server: smtp.gmail.com  # You can use another SMTP provider
          smtp-port: 587
          smtp-user: ${{ secrets.EMAIL_USERNAME }}
          smtp-password: ${{ secrets.EMAIL_PASSWORD }}
          secure: true
