name: Retrain Model
on:
  push:
    paths:
      - 'data/WA_Fn-UseC_-Telco-Customer-Churn.csv'  # Trigger retraining when this file changes

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        
      - name: Run retrain script
        run: |
          python scripts/data_preprocessing.py

      # Send email notification when retraining is complete
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          from: ${{ secrets.EMAIL_GITACTION }}  # Use GitHub Secrets for sensitive data
          to: ${{ secrets.EMAIL_GITACTION }}
          subject: 'Model Retraining Complete'
          body: 'The model retraining process has been successfully completed. Check the logs for details.'
          smtp-server: smtp.gmail.com  # Can be changed to other SMTP servers
          smtp-port: 587
          smtp-user: ${{ secrets.EMAIL_USERNAME }}
          smtp-password: ${{ secrets.EMAIL_PASSWORD }}
          secure: true

      # Send Telegram notification
      - name: Send Telegram notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=Model retraining completed successfully. Check the logs for more information."

